# SPDX-License-Identifier: Apache-2.0
# Copyright (c) The CivicCast Authors
"""A LAN-only native station must not depend on a host it cannot reach.

F-16 (sandbox newcomer re-walk `dd7f835f`, 2026-08-01): with the front door
missing, ``/docs`` and ``/openapi.json`` were the only routes on :8000 that
rendered at all -- and ``/docs`` fetched its Swagger UI JavaScript and CSS from
``cdn.jsdelivr.net``. A council-chamber station sits on a municipal LAN, often
firewalled outbound and sometimes air-gapped; a page whose only content arrives
from the public internet renders blank there and gives an operator a broken
screen with no explanation.

The finding was PARTLY imprecise and this module pins the corrected picture:

* ``/docs`` -- real. Swagger UI's bundle and stylesheet from
  ``cdn.jsdelivr.net``, plus a favicon from ``fastapi.tiangolo.com``.
* ``/redoc`` -- real, and WORSE than what was reported: ``cdn.jsdelivr.net``,
  ``fastapi.tiangolo.com`` AND ``fonts.googleapis.com``. The re-walk never
  probed it.
* ``/openapi.json`` -- NOT real. It is JSON generated by the app itself and
  contains no external host at all. It loads no Swagger and needs no network.

So the fix is scoped to the two HTML doc UIs, and ``/openapi.json`` -- the
actual machine-readable API contract, and the one an integrator needs -- stays
served.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from civiccast import app as app_module
from civiccast.app import create_app
from civiccast.native import station_runtime

# Spelled out here rather than imported, deliberately: these assertions must be
# able to RUN and FAIL against a tree that does not have the flag yet, which is
# exactly the tree the re-walk found. An import of a not-yet-existing name would
# collapse a real behavioural failure into a collection error.
LAN_ONLY_STATION_ENV_VAR = "CIVICCAST_LAN_ONLY_STATION"

EXTERNAL_HOST = re.compile(r"https?://([A-Za-z0-9.-]+)")

# Loopback and the station's own LAN address are not "external"; nothing else
# is reachable from a firewalled council chamber.
LOCAL_HOSTS = {"127.0.0.1", "localhost", "0.0.0.0", "::1"}


def _external_hosts(body: str) -> set[str]:
    return {host for host in EXTERNAL_HOST.findall(body) if host not in LOCAL_HOSTS}


@pytest.fixture
def lan_only_client(monkeypatch: pytest.MonkeyPatch) -> TestClient:
    monkeypatch.setenv(LAN_ONLY_STATION_ENV_VAR, "1")
    return TestClient(create_app())


def test_f16_a_lan_only_station_serves_no_page_that_loads_from_an_external_host(
    lan_only_client: TestClient,
) -> None:
    for route in ("/docs", "/redoc"):
        response = lan_only_client.get(route)
        assert response.status_code == 404, (
            f"{route} is served on a LAN-only station. FastAPI's built-in renderer for it "
            "pulls its JavaScript, CSS and fonts from cdn.jsdelivr.net / "
            "fastapi.tiangolo.com / fonts.googleapis.com -- none of which a firewalled "
            "council-chamber station can reach, so the operator gets a blank page. No "
            f"Swagger UI or ReDoc assets ship anywhere in this repo, so {route} cannot be "
            "served locally without vendoring them"
        )
        assert not _external_hosts(response.text), (
            f"{route}'s response still names an external host: "
            f"{sorted(_external_hosts(response.text))}"
        )


def test_f16_the_machine_readable_contract_is_still_served_and_is_self_contained(
    lan_only_client: TestClient,
) -> None:
    """The correction to the finding: /openapi.json never loaded Swagger from
    anywhere. Turning it off would remove a working, self-contained surface to
    fix a problem it does not have."""

    response = lan_only_client.get("/openapi.json")
    assert response.status_code == 200, (
        "/openapi.json is the machine-readable API contract, is generated by the app "
        "itself, and has no external dependency -- it must stay served on a LAN-only "
        "station"
    )
    assert not _external_hosts(response.text), (
        f"/openapi.json now names an external host: {sorted(_external_hosts(response.text))}"
    )


def test_f16_the_doc_uis_stay_available_where_the_network_is_not_the_constraint() -> None:
    """Deliberately NARROW. A container or cloud deployment reaching a CDN is
    not the defect; a municipal station that cannot is. Off by station, not off
    by default, so this change cannot quietly remove a working surface from a
    deployment that never had the problem."""

    client = TestClient(create_app())
    assert client.get("/docs").status_code == 200
    assert client.get("/redoc").status_code == 200


def test_f16_both_native_station_environments_declare_the_station_lan_only() -> None:
    """The flag has to reach the control-plane child on BOTH paths, or the
    pre-activation station -- exactly the state the re-walk was in when it
    found this -- keeps serving the CDN-backed page.

    Asserted against the shared producer both env builders merge in, so the
    activated and pre-activation paths cannot drift apart (the same coupling
    defect chain L closed for the portal dists).
    """

    assert getattr(app_module, "LAN_ONLY_STATION_ENV_VAR", None) == LAN_ONLY_STATION_ENV_VAR, (
        "civiccast.app must publish the env var name it reads, so the station-runtime "
        "side and the app side cannot drift to two different spellings of it"
    )

    producer = getattr(station_runtime, "lan_only_station_environment", None)
    assert producer is not None, (
        "civiccast.native.station_runtime must publish the LAN-only declaration as its "
        "own producer, the same shape as packaged_portal_environment"
    )
    assert producer() == {LAN_ONLY_STATION_ENV_VAR: "1"}

    source = station_runtime.__file__
    assert source
    text = Path(source).read_text(encoding="utf-8")
    assert text.count("lan_only_station_environment()") >= 2, (
        "lan_only_station_environment must be merged into BOTH "
        "pre_activation_control_plane_environment and load_native_station_environment; "
        "a station that is installed but not yet activated is still a LAN-only station"
    )


def test_f16_both_native_station_environments_declare_the_native_reported_version() -> None:
    """Chain J (2026-08-02): the exact same coupling defect class chain L
    closed for the LAN-only flag, closed here for the version override
    BEFORE it could ship broken. Without this, a station that is installed
    but not yet activated would silently report the WSL line's version over
    /health -- wrong on a pristine native station's very first health check,
    which is exactly when a newcomer walkthrough or install-verification step
    is most likely to look."""

    native_version_env_var = getattr(app_module, "NATIVE_REPORTED_VERSION_ENV_VAR", None)
    assert native_version_env_var == "CIVICCAST_NATIVE_REPORTED_VERSION", (
        "civiccast.app must publish the env var name it reads, so the station-runtime "
        "side and the app side cannot drift to two different spellings of it"
    )

    producer = getattr(station_runtime, "native_reported_version_environment", None)
    assert producer is not None, (
        "civiccast.native.station_runtime must publish the native-version declaration as "
        "its own producer, the same shape as lan_only_station_environment"
    )
    from civiccast import _native_version

    assert producer() == {native_version_env_var: _native_version.__version__}

    source = station_runtime.__file__
    assert source
    text = Path(source).read_text(encoding="utf-8")
    assert text.count("native_reported_version_environment()") >= 2, (
        "native_reported_version_environment must be merged into BOTH "
        "pre_activation_control_plane_environment and load_native_station_environment; "
        "a station that is installed but not yet activated must still report its own "
        "correct version, not silently fall back to the WSL line's"
    )
