# SPDX-License-Identifier: Apache-2.0
# Copyright (c) The CivicCast Authors
"""Live-caption worker seam for runtime, review queue, and HLS publication."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from civiccast.captions.models import AudioChunk, CaptionCue, CaptionHypothesis, CustomVocabulary
from civiccast.captions.pipeline import (
    CaptionHlsPipelineResult,
    CaptionPipeline,
    CaptionPipelineResult,
)
from civiccast.captions.review import (
    CaptionReviewAudioEvidence,
    CaptionReviewItemAlreadyExistsError,
    CaptionReviewItemResponse,
    CaptionReviewStore,
)
from civiccast.captions.runtime import CaptionRuntime
from civiccast.stream.config import HLS_SEGMENT_DURATION
from civiccast.stream.packager import SlateOnlyResult, VodPackageResult

AudioEvidenceFactory = Callable[[CaptionCue], CaptionReviewAudioEvidence]

if TYPE_CHECKING:
    from collections.abc import Mapping

    from civiccast.translate import TranslationProvider, TranslationTarget


@dataclass(frozen=True)
class LiveCaptionWorkerResult:
    """Result from one live-caption worker batch."""

    hypotheses: list[CaptionHypothesis]
    committed_review_items: list[CaptionReviewItemResponse]
    duplicate_review_item_ids: list[str]
    hls_result: CaptionHlsPipelineResult | None
    # Pending hypotheses the stabilizer expired without re-confirmation. Never
    # committed/never on-air -- they still get a review row (folded into
    # committed_review_items, same store, same path) but are broken out here
    # too so a caller can count the drop instead of it hiding in the total.
    expired_unconfirmed_cues: list[CaptionCue] = field(default_factory=list)


class LiveCaptionWorker:
    """Process live audio chunks into stable review rows and optional HLS captions.

    The worker owns one long-lived :class:`CaptionPipeline` so the two-window
    stabilization contract survives across small live-audio batches. Production
    live capture can feed PCM chunks into this seam; tests can use a fake
    runtime without requiring GPU model execution.
    """

    def __init__(
        self,
        runtime: CaptionRuntime,
        review_store: CaptionReviewStore,
        *,
        asset_id: str,
        vocabulary: CustomVocabulary | None = None,
        reviewer_note: str = "Auto-generated by local caption runtime.",
        package: VodPackageResult | SlateOnlyResult | None = None,
        language: str = "en",
        language_name: str = "English",
        translation_provider: TranslationProvider | None = None,
        translation_targets: list[TranslationTarget] | None = None,
        translation_glossary: Mapping[str, str] | None = None,
        segment_duration: int = HLS_SEGMENT_DURATION,
        pipeline: CaptionPipeline | None = None,
    ) -> None:
        self._pipeline = pipeline or CaptionPipeline(runtime)
        self._review_store = review_store
        self._asset_id = asset_id
        self._vocabulary = vocabulary
        self._reviewer_note = reviewer_note
        self._package = package
        self._language = language
        self._language_name = language_name
        self._translation_provider = translation_provider
        self._translation_targets = translation_targets or []
        self._translation_glossary = translation_glossary
        self._segment_duration = segment_duration

    def process_batch(
        self,
        chunks: list[AudioChunk],
        *,
        audio_evidence_factory: AudioEvidenceFactory | None = None,
    ) -> LiveCaptionWorkerResult:
        """Process one live-audio batch and persist any newly stable cues."""

        if self._package is None:
            caption_result = self._pipeline.process(
                chunks,
                asset_id=self._asset_id,
                vocabulary=self._vocabulary,
                reviewer_note=self._reviewer_note,
            )
            hls_result = None
        else:
            hls_result = self._pipeline.process_and_publish_hls(
                chunks,
                asset_id=self._asset_id,
                package=self._package,
                vocabulary=self._vocabulary,
                reviewer_note=self._reviewer_note,
                language=self._language,
                name=self._language_name,
                translation_provider=self._translation_provider,
                translation_targets=self._translation_targets,
                translation_glossary=self._translation_glossary,
                segment_duration=self._segment_duration,
            )
            caption_result = hls_result.caption_result

        committed_items, duplicates = self._persist_review_items(
            caption_result,
            audio_evidence_factory=audio_evidence_factory,
        )

        return LiveCaptionWorkerResult(
            hypotheses=caption_result.hypotheses,
            committed_review_items=committed_items,
            duplicate_review_item_ids=duplicates,
            hls_result=hls_result,
            expired_unconfirmed_cues=caption_result.expired_unconfirmed_cues,
        )

    def flush(self) -> LiveCaptionWorkerResult:
        """Commit every cue still pending at end-of-stream/channel-stop.

        There is no second transcription pass once the caller knows a
        stream/channel has ended, so anything still pending must be
        committed now (flagged low-confidence unless it already earned
        re-confirmation) or lost forever. Flushed cues persist through the
        exact same review-store and HLS/active-VTT publication path as
        :meth:`process_batch`. Safe to call repeatedly: once the stabilizer
        has no pending cues, later calls persist nothing new.
        """

        if self._package is None:
            caption_result = self._pipeline.flush(
                asset_id=self._asset_id,
                reviewer_note=self._reviewer_note,
            )
            hls_result = None
        else:
            hls_result = self._pipeline.flush_and_publish_hls(
                asset_id=self._asset_id,
                package=self._package,
                reviewer_note=self._reviewer_note,
                language=self._language,
                name=self._language_name,
                translation_provider=self._translation_provider,
                translation_targets=self._translation_targets,
                translation_glossary=self._translation_glossary,
                segment_duration=self._segment_duration,
            )
            caption_result = hls_result.caption_result

        committed_items, duplicates = self._persist_review_items(caption_result)

        return LiveCaptionWorkerResult(
            hypotheses=caption_result.hypotheses,
            committed_review_items=committed_items,
            duplicate_review_item_ids=duplicates,
            hls_result=hls_result,
        )

    def _persist_review_items(
        self,
        caption_result: CaptionPipelineResult,
        *,
        audio_evidence_factory: AudioEvidenceFactory | None = None,
    ) -> tuple[list[CaptionReviewItemResponse], list[str]]:
        committed_items: list[CaptionReviewItemResponse] = []
        duplicates: list[str] = []
        for item in caption_result.review_items:
            payload = (
                item.model_copy(update={"audio_evidence": audio_evidence_factory(item.cue)})
                if audio_evidence_factory is not None
                else item
            )
            try:
                committed_items.append(self._review_store.create(payload))
            except CaptionReviewItemAlreadyExistsError:
                duplicates.append(item.review_item_id)
        return committed_items, duplicates

    def committed_cues(self) -> list[CaptionCue]:
        """Return the complete immutable cue set known to this live worker."""

        return self._pipeline.committed()
