"""Generate the HTTP API inventory from the live FastAPI app (documentation tool, not product code).

  "C:/Program Files/CivicCast (Native)/runtime/python.exe" gen_api_inventory.py <out.md> <repo-root>

Builds the app object (no server, no database) and reads its OpenAPI document, so the table cannot drift from the code.
"""

import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, sys.argv[2])

from civiccast._version import __version__
from civiccast.app import create_app

PIPE = "\\|"
doc = create_app().openapi()
groups = defaultdict(list)
for path, methods in sorted(doc["paths"].items()):
    parts = [p for p in path.split("/") if p]
    if len(parts) >= 3 and parts[0] == "api":
        key = f"/api/{parts[1]}/{parts[2]}"
    elif len(parts) >= 2 and parts[0] == "api":
        key = f"/api/{parts[1]}"
    else:
        key = "(root / protocol endpoints)"
    for method, op in sorted(methods.items()):
        if method.lower() not in {"get", "post", "put", "patch", "delete", "head", "options"}:
            continue
        summary = (op.get("summary") or "").replace("|", PIPE)
        desc = (op.get("description") or "").strip().split("\n")[0].replace("|", PIPE)
        body = ""
        rb = op.get("requestBody", {}).get("content", {})
        if rb:
            body = ", ".join(sorted(rb))
        codes = ", ".join(sorted(op.get("responses", {})))
        groups[key].append((method.upper(), path, summary, desc, body, codes))

total = sum(len(v) for v in groups.values())
out = [
    f"# HTTP API inventory (generated from the FastAPI app, civiccast {__version__})",
    "",
    f"{len(doc['paths'])} paths, {total} operations, {len(groups)} groups. Generated by "
    "`ops/docs-sprint/tools/gen_api_inventory.py`; do not edit by hand.",
    "",
    "Staff routes (`/api/staff/*`) require a bearer token and a role; public routes do not. See "
    "`docs/ops/staff-route-protection.md` and the role matrix in `inventory/screens/_shell-navigation-and-roles.md`.",
    "",
]
for key in sorted(groups):
    out += [
        f"## {key}",
        "",
        "| Method | Path | Summary | Body | Responses |",
        "| --- | --- | --- | --- | --- |",
    ]
    for method, path, summary, desc, body, codes in groups[key]:
        text = summary if summary else desc
        out.append(f"| {method} | `{path}` | {text} | {body} | {codes} |")
    out.append("")
Path(sys.argv[1]).write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
print(total, "operations written in", len(groups), "groups")
