"""Generate the environment-variable inventory by scanning the source (documentation tool, not product code).

  python gen_env_inventory.py <out.md> <repo-root>

Lists every CIVICCAST_* / CIVICAST_* name found in product code, where it appears, and whether any prose doc mentions it.
The one-C spelling (CIVICAST_) is a known bug class in this repo; both spellings are listed so the mismatch is visible.
"""

import contextlib
import re
import sys
from collections import defaultdict
from pathlib import Path

root = Path(sys.argv[2])
NAME = re.compile(r"\bCIVIC{1,2}AST_[A-Z0-9_]+\b")
CODE_DIRS = ["civiccast", "scripts", "sandbox-lab", "tools"]
CODE_EXT = {".py", ".rs", ".ts", ".tsx", ".ps1", ".sh", ".yml", ".yaml", ".toml", ".json", ".nsh"}
SKIP = {"node_modules", "target", "dist", "__pycache__", ".venv", "site-packages"}

seen = defaultdict(list)
for d in CODE_DIRS:
    base = root / d
    if not base.exists():
        continue
    for p in base.rglob("*"):
        if not p.is_file() or p.suffix.lower() not in CODE_EXT or any(s in p.parts for s in SKIP):
            continue
        if p.stat().st_size > 2_000_000:
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        is_test = "tests" in p.parts or p.name.startswith("test_")
        for i, line in enumerate(text.splitlines(), 1):
            for m in NAME.findall(line):
                seen[m].append((p.relative_to(root).as_posix(), i, is_test))

doc_text = ""
for p in list((root / "docs").rglob("*.md")) + list(root.glob("*.md")):
    if "history" in p.parts or "evidence" in p.parts:
        continue
    with contextlib.suppress(OSError):
        doc_text += p.read_text(encoding="utf-8", errors="replace") + "\n"

names = sorted(seen)
one_c = [n for n in names if n.startswith("CIVICAST_")]
out = [
    "# Environment variable inventory (generated by scanning product source)",
    "",
    f"{len(names)} distinct names ({len(one_c)} use the one-C `CIVICAST_` spelling). Generated by "
    "`ops/docs-sprint/tools/gen_env_inventory.py`; do not edit by hand.",
    "",
    "`Documented` = the name appears in a prose doc under `docs/` or a root `.md` file. "
    "`Prod refs` counts non-test source references; the first location is shown.",
    "",
    "| Name | Prod refs | First location | Documented | Notes |",
    "| --- | --- | --- | --- | --- |",
]
for n in names:
    prod = [x for x in seen[n] if not x[2]]
    first = f"{prod[0][0]}:{prod[0][1]}" if prod else "(tests only)"
    documented = "yes" if n in doc_text else "no"
    note = "one-C spelling: check it is not silently inert" if n.startswith("CIVICAST_") else ""
    out.append(f"| `{n}` | {len(prod)} | {first} | {documented} | {note} |")
Path(sys.argv[1]).write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
print(len(names), "names;", sum(1 for n in names if n in doc_text), "documented")
