"""Generate the CLI inventory from the Typer app itself (documentation tool, not product code).

Run with a Python that has CivicCast's dependencies (the station runtime works):
  "C:/Program Files/CivicCast (Native)/runtime/python.exe" gen_cli_inventory.py <out.md> <repo-root>
The repo root is put on sys.path explicitly because the station runtime ignores PYTHONPATH.
"""

import sys
from pathlib import Path

sys.path.insert(0, sys.argv[2])

import typer

from civiccast import cli as c
from civiccast._version import __version__

PIPE = "\\|"

root = typer.main.get_command(c.app)
rows = []


def walk(cmd, path):
    subs = getattr(cmd, "commands", None)
    if subs:
        for name in sorted(subs):
            walk(subs[name], [*path, name])
    else:
        rows.append((path, cmd))


walk(root, ["civiccast"])
out = [
    f"# CLI inventory (generated from the Typer app, civiccast {__version__})",
    "",
    f"{len(rows)} commands. Generated by `ops/docs-sprint/tools/gen_cli_inventory.py`; do not edit by hand.",
    "",
]
group = None
for path, cmd in rows:
    g = path[1] if len(path) > 2 else "(top level)"
    if g != group:
        out += [f"## {g}", ""]
        group = g
    help_ = (cmd.help or "").strip().split("\n\n")[0].replace("\n", " ")
    out.append("### `" + " ".join(path) + "`")
    out.append("")
    out.append(help_ or "_(no help text)_")
    out.append("")
    params = list(cmd.params)
    if params:
        out.append("| Option / argument | Type | Default | Env var | What it does |")
        out.append("| --- | --- | --- | --- | --- |")
        for p in params:
            opts = getattr(p, "opts", None)
            is_option = hasattr(p, "secondary_opts")
            names = ", ".join(opts) if is_option and opts else "<" + str(p.name) + ">"
            t = getattr(p.type, "name", str(p.type))
            d = "" if p.default is None or p.default is ... else str(p.default)
            env = getattr(p, "envvar", None) or ""
            if isinstance(env, (list, tuple)):
                env = ", ".join(env)
            h = (getattr(p, "help", "") or "").replace("|", PIPE).replace("\n", " ")
            req = " (required)" if getattr(p, "required", False) else ""
            out.append(
                "| `"
                + names
                + "`"
                + req
                + " | "
                + str(t)
                + " | "
                + d.replace("|", PIPE)
                + " | "
                + str(env)
                + " | "
                + h
                + " |"
            )
        out.append("")
with open(sys.argv[1], "w", encoding="utf-8", newline="\n") as fh:
    fh.write("\n".join(out) + "\n")
print(len(rows), "commands written")
