# SPDX-License-Identifier: Apache-2.0
# Copyright (c) The CivicCast Authors
"""Pure, deterministic config-file renderers for the provisioned PostgreSQL
server.

NATS JetStream was removed from the product entirely (owner decision
2026-08-20, ADR 0023 "NATS removed -- in-process event bus", which supersedes
ADR 0001); this module no longer renders a ``nats-server.conf``.

Every function here takes plain values and returns a plain string -- no I/O,
no Windows import, no randomness -- so the exact bytes a real install would
write are unit-testable on any OS. The orchestrator (:mod:`civiccast.native.
provision.orchestrator`) calls these to produce content, then hands that
content to a ``write_*`` seam; this module never touches a filesystem.

Scope note (WS5 D4 "postgresql.conf/pg_hba.conf minimal deltas the product
needs"): these renderers produce the WHOLE file content for the product's
OWN, product-private data directory (never a shared/system PostgreSQL
install), so a full deterministic rewrite is safe and simpler than patching
generated defaults in place -- this is documented here because it is a
deliberate scope choice, not an oversight.
"""

from __future__ import annotations

_GENERATED_BANNER = (
    "# Generated by civiccast.native.provision -- do not hand-edit.\n"
    "# A repair run overwrites this file from the same deterministic template.\n"
)


def _validate_host(host: str) -> str:
    if not host or not host.strip():
        raise ValueError("host must not be empty")
    return host.strip()


def _validate_port(port: int) -> int:
    if isinstance(port, bool) or not (1 <= port <= 65535):
        raise ValueError(f"port must be an integer between 1 and 65535, got {port!r}")
    return port


def render_postgresql_conf(
    *,
    host: str = "127.0.0.1",
    port: int = 5432,
    max_connections: int = 100,
) -> str:
    """Render the product's private ``postgresql.conf``.

    Binds ONLY to ``host`` (default the loopback address the native
    supervisor's ``postgres_child_spec`` launches against --
    :mod:`civiccast.native.supervisor.children`), disables the Unix-domain
    socket directory (meaningless -- and a startup hazard -- on Windows), and
    turns SSL off (the control-plane connection is local-loopback-only; there
    is no external message-bus boundary to secure since NATS JetStream was
    removed from the product in favor of the in-process event bus -- owner
    decision 2026-08-20, ADR 0023).
    """

    host = _validate_host(host)
    port = _validate_port(port)
    if isinstance(max_connections, bool) or max_connections < 1:
        raise ValueError(f"max_connections must be a positive integer, got {max_connections!r}")

    lines = [
        _GENERATED_BANNER,
        f"listen_addresses = '{host}'",
        f"port = {port}",
        f"max_connections = {max_connections}",
        # Windows has no Unix-domain sockets; an empty list disables the
        # attempt outright rather than leaving PostgreSQL's platform default.
        "unix_socket_directories = ''",
        # Loopback-only control-plane connection; there is no message-bus TLS
        # boundary to mirror since NATS JetStream was removed from the
        # product (owner decision 2026-08-20, ADR 0023).
        "ssl = off",
        "logging_collector = off",
    ]
    return "\n".join(lines) + "\n"


def render_pg_hba_conf(*, host: str = "127.0.0.1") -> str:
    """Render the product's private ``pg_hba.conf``: exactly one rule,
    scram-sha-256 authentication for the exact loopback host CivicCast's
    control plane connects from. No wildcard, no trust method, no remote
    entry -- absence of a matching rule is PostgreSQL's own fail-closed
    default (connection refused).
    """

    host = _validate_host(host)
    cidr = f"{host}/32"
    lines = [
        _GENERATED_BANNER,
        "# TYPE  DATABASE  USER  ADDRESS         METHOD",
        f"host    all       all   {cidr}    scram-sha-256",
    ]
    return "\n".join(lines) + "\n"


def render_pg_hba_trust_conf(*, host: str = "127.0.0.1") -> str:
    """Render the TRANSIENT ``pg_hba.conf`` used ONLY during the adoption
    credential-reset maintenance window (N-15).

    When an uninstall (chain M / security fix F-02) has deleted the
    ``DatabaseUrl`` registry credential but deliberately PRESERVED the product
    data directory, the surviving cluster's service-role password lives
    nowhere on disk and cannot be reconstructed -- so a reinstall must
    re-establish a fresh credential on the SAME cluster (data preserved) to
    adopt it. Re-establishing that credential requires a superuser connection,
    which the reinstaller does not have a password for; this file grants a
    single, loopback-only ``trust`` rule for the brief window in which
    :func:`civiccast.native.provision.seams.reset_cluster_credential` starts
    the cluster, verifies it is a CivicCast-provisioned cluster, and runs
    ``ALTER ROLE ... PASSWORD``. It is ALWAYS overwritten by
    :func:`render_pg_hba_conf`'s scram-sha-256 rule before the cluster is
    handed to the supervisor -- the ``trust`` grant never outlives the reset
    maintenance start (see that seam's stop-in-``finally`` contract).

    Same shape as :func:`render_pg_hba_conf`: exactly one loopback rule, no
    wildcard host, no remote entry -- the ONLY difference is the METHOD
    column (``trust`` vs ``scram-sha-256``), and even that is scoped to the
    single loopback address the control plane connects from.
    """

    host = _validate_host(host)
    cidr = f"{host}/32"
    lines = [
        _GENERATED_BANNER,
        "# TRANSIENT adoption-window auth ONLY -- overwritten with the resting\n"
        "# scram rule before the cluster is handed to the supervisor. See "
        "render_pg_hba_trust_conf.",
        "# TYPE  DATABASE  USER  ADDRESS         METHOD",
        f"host    all       all   {cidr}    trust",
    ]
    return "\n".join(lines) + "\n"


__all__ = [
    "render_pg_hba_conf",
    "render_pg_hba_trust_conf",
    "render_postgresql_conf",
]
