# SPDX-License-Identifier: Apache-2.0
# Copyright (c) The CivicCast Authors
"""Pure, deterministic config-file renderers for the provisioned PostgreSQL
and NATS servers.

Every function here takes plain values and returns a plain string -- no I/O,
no Windows import, no randomness -- so the exact bytes a real install would
write are unit-testable on any OS. The orchestrator (:mod:`civiccast.native.
provision.orchestrator`) calls these to produce content, then hands that
content to a ``write_*`` seam; this module never touches a filesystem.

Scope note (WS5 D4 "postgresql.conf/pg_hba.conf minimal deltas the product
needs"): these renderers produce the WHOLE file content for the product's
OWN, product-private data directory (never a shared/system PostgreSQL
install), so a full deterministic rewrite is safe and simpler than patching
generated defaults in place -- this is documented here because it is a
deliberate scope choice, not an oversight.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from civiccast.native.provision.models import NatsTlsFiles

_GENERATED_BANNER = (
    "# Generated by civiccast.native.provision -- do not hand-edit.\n"
    "# A repair run overwrites this file from the same deterministic template.\n"
)


def _validate_host(host: str) -> str:
    if not host or not host.strip():
        raise ValueError("host must not be empty")
    return host.strip()


def _validate_port(port: int) -> int:
    if isinstance(port, bool) or not (1 <= port <= 65535):
        raise ValueError(f"port must be an integer between 1 and 65535, got {port!r}")
    return port


def render_postgresql_conf(
    *,
    host: str = "127.0.0.1",
    port: int = 5432,
    max_connections: int = 100,
) -> str:
    """Render the product's private ``postgresql.conf``.

    Binds ONLY to ``host`` (default the loopback address the native
    supervisor's ``postgres_child_spec`` launches against --
    :mod:`civiccast.native.supervisor.children`), disables the Unix-domain
    socket directory (meaningless -- and a startup hazard -- on Windows), and
    turns SSL off (the control-plane connection is local-loopback-only; NATS,
    not Postgres, is the mTLS boundary per
    :mod:`civiccast.platform.broker_config`).
    """

    host = _validate_host(host)
    port = _validate_port(port)
    if isinstance(max_connections, bool) or max_connections < 1:
        raise ValueError(f"max_connections must be a positive integer, got {max_connections!r}")

    lines = [
        _GENERATED_BANNER,
        f"listen_addresses = '{host}'",
        f"port = {port}",
        f"max_connections = {max_connections}",
        # Windows has no Unix-domain sockets; an empty list disables the
        # attempt outright rather than leaving PostgreSQL's platform default.
        "unix_socket_directories = ''",
        # Loopback-only control-plane connection; NATS carries the mTLS
        # boundary for anything that leaves the box.
        "ssl = off",
        "logging_collector = off",
    ]
    return "\n".join(lines) + "\n"


def render_pg_hba_conf(*, host: str = "127.0.0.1") -> str:
    """Render the product's private ``pg_hba.conf``: exactly one rule,
    scram-sha-256 authentication for the exact loopback host CivicCast's
    control plane connects from. No wildcard, no trust method, no remote
    entry -- absence of a matching rule is PostgreSQL's own fail-closed
    default (connection refused).
    """

    host = _validate_host(host)
    cidr = f"{host}/32"
    lines = [
        _GENERATED_BANNER,
        "# TYPE  DATABASE  USER  ADDRESS         METHOD",
        f"host    all       all   {cidr}    scram-sha-256",
    ]
    return "\n".join(lines) + "\n"


def render_pg_hba_trust_conf(*, host: str = "127.0.0.1") -> str:
    """Render the TRANSIENT ``pg_hba.conf`` used ONLY during the adoption
    credential-reset maintenance window (N-15).

    When an uninstall (chain M / security fix F-02) has deleted the
    ``DatabaseUrl`` registry credential but deliberately PRESERVED the product
    data directory, the surviving cluster's service-role password lives
    nowhere on disk and cannot be reconstructed -- so a reinstall must
    re-establish a fresh credential on the SAME cluster (data preserved) to
    adopt it. Re-establishing that credential requires a superuser connection,
    which the reinstaller does not have a password for; this file grants a
    single, loopback-only ``trust`` rule for the brief window in which
    :func:`civiccast.native.provision.seams.reset_cluster_credential` starts
    the cluster, verifies it is a CivicCast-provisioned cluster, and runs
    ``ALTER ROLE ... PASSWORD``. It is ALWAYS overwritten by
    :func:`render_pg_hba_conf`'s scram-sha-256 rule before the cluster is
    handed to the supervisor -- the ``trust`` grant never outlives the reset
    maintenance start (see that seam's stop-in-``finally`` contract).

    Same shape as :func:`render_pg_hba_conf`: exactly one loopback rule, no
    wildcard host, no remote entry -- the ONLY difference is the METHOD
    column (``trust`` vs ``scram-sha-256``), and even that is scoped to the
    single loopback address the control plane connects from.
    """

    host = _validate_host(host)
    cidr = f"{host}/32"
    lines = [
        _GENERATED_BANNER,
        "# TRANSIENT adoption-window auth ONLY -- overwritten with the resting\n"
        "# scram rule before the cluster is handed to the supervisor. See "
        "render_pg_hba_trust_conf.",
        "# TYPE  DATABASE  USER  ADDRESS         METHOD",
        f"host    all       all   {cidr}    trust",
    ]
    return "\n".join(lines) + "\n"


class NatsConfRender(BaseModel):
    """The rendered NATS config content plus whether it carries a ``tls {}``
    block, so a caller (or a test) can assert TLS presence without
    re-parsing the config text."""

    model_config = ConfigDict(extra="forbid")

    content: str
    tls_enabled: bool


def _escape_conf_string(value: str) -> str:
    """Escape a value for embedding in a NATS server config double-quoted
    string (HOCON-like syntax: backslashes and double quotes are the only
    characters that are load-bearing to escape for a Windows path)."""

    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_nats_conf(
    *,
    host: str = "127.0.0.1",
    port: int = 4222,
    store_dir: str,
    tls: NatsTlsFiles | None = None,
) -> NatsConfRender:
    """Render the ``nats-server`` config file.

    JetStream is always enabled with ``store_dir`` (D4: NATS "data/store dir
    provisioning"). When ``tls`` is supplied, a ``tls {}`` block is emitted
    with ``verify: true`` (client-cert-required mTLS), matching
    :class:`civiccast.platform.broker_config.NATSMTLSFiles` /
    :func:`civiccast.platform.broker_config.BrokerConfig.__post_init__`'s
    production requirement that ``CIVICCAST_NATS_URL`` use ``tls://``.
    Certificate ISSUANCE is out of this module's scope -- see
    :class:`civiccast.native.provision.models.NatsTlsFiles`'s docstring.
    """

    host = _validate_host(host)
    port = _validate_port(port)
    if not store_dir or not store_dir.strip():
        raise ValueError("store_dir must not be empty")

    lines = [
        _GENERATED_BANNER,
        f'host: "{_escape_conf_string(host)}"',
        f"port: {port}",
        "jetstream {",
        f'  store_dir: "{_escape_conf_string(store_dir)}"',
        "}",
        # Lame-duck drain settings. The unconfigured default
        # lame_duck_duration is 2 MINUTES, vastly longer than the supervisor's
        # graceful_stop_deadline_seconds (15s default); nats-server 2.14.3
        # enforces a HARD 30-SECOND FLOOR on lame_duck_duration (verified
        # against the real pack-cache binary: ``nats-server.exe -t -c <conf>``
        # rejects a 5s value with "invalid lame_duck_duration of 5s, minimum is
        # 30 seconds"), so this pins the enforced MINIMUM, plus a short grace
        # period so the drain begins promptly once a signal lands rather than
        # waiting needlessly.
        #
        # CORRECTION (2026-07-31, F3) -- this is FORWARD-LOOKING config, NOT a
        # fix for the supervisor's stop path, which is what the G4(a) comment
        # here previously claimed. MEASURED on Windows: ``nats-server --signal
        # ldm=<pid>`` fails with "Access is denied" PID-INDEPENDENTLY, because
        # that flag routes through the SCM (OpenService) and this nats-server is
        # a plain child process, not a registered service. The signal never
        # arrives, so NO lame_duck_* value can change what the supervisor's stop
        # does: on Windows nats is ended by the shared D5 deadline +
        # TerminateProcess escalation (the accepted beta contract). These lines
        # are kept because they are correct, validated configuration -- they
        # would take effect for any drain the server DOES enter (a platform
        # where the signal works, or a future in-process drain command) -- and
        # because 30s beats a silent 2-minute default either way.
        'lame_duck_duration: "30s"',
        'lame_duck_grace_period: "5s"',
    ]
    tls_enabled = tls is not None
    if tls is not None:
        lines += [
            "tls {",
            f'  ca_file: "{_escape_conf_string(tls.ca_file)}"',
            f'  cert_file: "{_escape_conf_string(tls.cert_file)}"',
            f'  key_file: "{_escape_conf_string(tls.key_file)}"',
            "  verify: true",
            "}",
        ]
    content = "\n".join(lines) + "\n"
    return NatsConfRender(content=content, tls_enabled=tls_enabled)


__all__ = [
    "NatsConfRender",
    "render_nats_conf",
    "render_pg_hba_conf",
    "render_pg_hba_trust_conf",
    "render_postgresql_conf",
]
